---
- name: copy backend to ec2 instance
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: create binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: launch server for backend
  become: true
  shell: |
    cd /home/ubuntu
    pm2 start npm \
    --name backend \
    --start

- name: "Installing npm"
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh


- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.10 && nvm alias default 0.10"
    creates=/home/{{ ansible_user_id }}/.nvm/alias

- name: "Installing pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present